name: Deploy Torchlight Engine
on: [ push, pull_request ]
jobs:
  vercel:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code  ...
 
      - name: Cache Dependencies ...
 
      - name: Setup Node 14 ...
 
      - name: Build ...
 
      - name: Run Tests Locally ...
 
      - name: Deploy to Staging ...
 
      - name: Run Tests Against Vercel ...
 
      - name: Deploy to Production ...
